version: '3.7'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - sneteste

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5698:5698
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - sneteste

volumes:
  api:
  database_postgres:

networks:
  sneteste: